-- MySQL Script generated by MySQL Workbench
-- Tue 15 Aug 2017 20:36:00 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema availability_calendar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema availability_calendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `availability_calendar` DEFAULT CHARACTER SET latin1 ;
USE `availability_calendar` ;

-- -----------------------------------------------------
-- Table `availability_calendar`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`groups` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`login_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`login_attempts` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`users` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `previous_project` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`users_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`users_settings` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`users_settings` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `attendee_reminder_email` TINYINT(1) NULL DEFAULT 1,
  `info_update` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_users_settings_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_settings_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `availability_calendar`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`users_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`users_groups` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`users_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_users_groups` (`user_id` ASC, `group_id` ASC),
  INDEX `fk_users_groups_users1_idx` (`user_id` ASC),
  INDEX `fk_users_groups_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `availability_calendar`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `availability_calendar`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`projects` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(99) NOT NULL,
  `owner_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Projects have at least one day and one step. They must also have unique names. ';


-- -----------------------------------------------------
-- Table `availability_calendar`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`positions` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `running_day` TINYINT UNSIGNED NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `description` VARCHAR(9000) NULL,
  `max_vol` MEDIUMINT UNSIGNED NULL,
  `is_draft` TINYINT(1) UNSIGNED NOT NULL,
  `last_update` DATETIME NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_positions_projects_idx` (`project_id` ASC),
  CONSTRAINT `fk_positions_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `availability_calendar`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Each project is broken into days and each day has positions. Positions are the individual parts of the project, and are the things the users interact with by volunteering their availability. ';


-- -----------------------------------------------------
-- Table `availability_calendar`.`users_positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`users_positions` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`users_positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `position_id` INT UNSIGNED NOT NULL,
  `calendar_date` DATE NOT NULL,
  INDEX `fk_users_positions_users_idx` (`user_id` ASC),
  INDEX `fk_users_positions_positions_idx` (`position_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_positions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `availability_calendar`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_positions_positions`
    FOREIGN KEY (`position_id`)
    REFERENCES `availability_calendar`.`positions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`info` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `body` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`cancelled_dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`cancelled_dates` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`cancelled_dates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cancelled_date` DATE NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cancelled_dates_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_cancelled_dates_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `availability_calendar`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `availability_calendar`.`old_positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `availability_calendar`.`old_positions` ;

CREATE TABLE IF NOT EXISTS `availability_calendar`.`old_positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `old_position_id` INT UNSIGNED NOT NULL,
  `running_day` TINYINT UNSIGNED NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `description` VARCHAR(9000) NULL,
  `max_vol` MEDIUMINT UNSIGNED NULL,
  `is_draft` TINYINT(1) UNSIGNED NOT NULL,
  `last_update` DATETIME NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_old_positions_positions_id_idx` (`old_position_id` ASC),
  INDEX `fk_old_positions_projects_id_idx` (`project_id` ASC),
  CONSTRAINT `fk_old_positions_positions_id`
    FOREIGN KEY (`old_position_id`)
    REFERENCES `availability_calendar`.`positions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_old_positions_projects_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `availability_calendar`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Archives old position edits. ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
